msz/market/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'msz.market.views',
    url(r'^category/(?P<pk>\d+)/$', 'category_info', name='category_info'),
    url(r'^buy/$', 'buy', name='buy'),
)

msz/union/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'msz.union.views',
    url(r'^login/$', 'login', name='login'),
    url(r'^logout/$', 'logout', name='logout'),

    url(r'^index/$', 'index', name='index'),
    url(r'^company/$', 'company_detail', name='company_detail'),
    url(r'^company/(?P<pk>\d+)/update/$', 'company_update', name='company_update'),
    url(r'^goods/category/$', 'category_list', name='category_list'),
    url(r'^goods/category/create/$', 'category_create', name='category_create'),
    url(r'^goods/category/(?P<pk>\d+)/update/$', 'category_update', name='category_update'),
    url(r'^goods/product/$', 'product_list', name='product_list'),
    url(r'^goods/product/create/$', 'product_create', name='product_create'),
    url(r'^goods/product/(?P<pk>\d+)/update/$', 'product_update', name='product_update'),
)

msz/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from msz.market.views import index

admin.autodiscover()

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'demo_tmp.views.home', name='home'),
    # url(r'^msz/', include('msz.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^captcha/', include('captcha.urls')),
    url(r'^i18n/setlang/$', 'django.views.i18n.set_language', name='set_language'),
    url(r'^$', index, name='index'),
    url(r'', include('msz.market.urls', namespace='market')),
    # union
    url(r'^union/', include('msz.union.urls', namespace='union')),
)


if settings.DEBUG:
    urlpatterns = patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns

    from django.views.generic import TemplateView
    urlpatterns += patterns(
        '',
        url(r'', include('dj_kits.magicpages.urls')),
        url(r'^$', TemplateView.as_view(template_name='index.html')),
    )


if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

msz/market/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from model_utils.models import TimeStampedModel


@python_2_unicode_compatible
class Company(TimeStampedModel):
    name = models.CharField(max_length=50, verbose_name=_(u"名称"))
    mobile = models.CharField(max_length=20, verbose_name=_(u'手机号'), blank=True)
    tel = models.CharField(max_length=20, verbose_name=_(u"联系方式"), blank=True)
    image = models.ImageField(upload_to='market/category/', blank=True, verbose_name=_(u"公司图片"))
    description = models.TextField(blank=True, verbose_name=_(u"描述"))
    address = models.CharField(max_length=128, verbose_name=_(u"地址"), blank=True)
    manager = models.CharField(max_length=20, verbose_name=_(u"负责人"))

    class Meta:
        verbose_name = _(u"公司")
        verbose_name_plural = _(u"公司")

    def __str__(self):
        return self.name

    def get_image_url(self):
        if self.image:
            return self.image.url
        return ''


@python_2_unicode_compatible
class Category(TimeStampedModel):
    name = models.CharField(max_length=128, verbose_name=_(u"分类名称"), unique=True)
    info = models.CharField(max_length=50, verbose_name=_(u"简短优势"))
    image = models.ImageField(upload_to='market/category/', blank=True, verbose_name=_(u"分类图片"))
    is_delete = models.BooleanField(default=False, verbose_name=_(u"是否删除"))
    code = models.CharField(max_length=50, blank=True, null=True, verbose_name=_(u"分类编号"))
    description = models.TextField(blank=True, verbose_name=_(u"描述"))

    class Meta:
        verbose_name = _(u"分类")
        verbose_name_plural = _(u"分类")

    def __str__(self):
        return self.name

    def get_image_url(self):
        if self.image:
            return self.image.url
        return ''

    @property
    def products(self):
        return Product.objects.filter(category=self)


@python_2_unicode_compatible
class Product(TimeStampedModel):
    name = models.CharField(max_length=128, verbose_name=_(u"名称"), unique=True)
    code = models.CharField(max_length=50, blank=True, null=True, verbose_name=_(u"商品编码"))
    category = models.ForeignKey(Category, verbose_name=_(u"所属分类"))
    info = models.CharField(max_length=50, verbose_name=_(u"简短优势"))
    image = models.ImageField(upload_to='market/product/', blank=True, verbose_name=_(u"商品图片图片"))
    is_delete = models.BooleanField(default=False, verbose_name=_(u"是否删除"))
    description = models.TextField(blank=True, verbose_name=_(u"描述"))
    materials = models.TextField(blank=True, verbose_name=_(u"配料"))

    class Meta:
        verbose_name = _(u"商品表")
        verbose_name_plural = _(u"商品表")

    def __str__(self):
        return self.name

    def get_image_url(self):
        if self.image:
            return self.image.url
        return ''


@python_2_unicode_compatible
class HomePic(TimeStampedModel):
    name = models.CharField(max_length=64, verbose_name=_(u"名称"))
    image = models.ImageField(upload_to='market/', blank=True, verbose_name=_(u"首页轮播图片"))
    is_active = models.BooleanField(default=False, verbose_name=_(u"是否是首张图片"))

    class Meta:
        verbose_name = _(u"首页轮播图")
        verbose_name_plural = _(u"首页轮播图")

    def __str__(self):
        return self.name

    def get_image_url(self):
        if self.image:
            return self.image.url
        return ''

msz/core/forms.py
# -*- coding: utf-8 -*-
import re
import cStringIO
from crispy_forms.bootstrap import FormActions
from crispy_forms.layout import Reset, Submit, Layout, Div, HTML
from django.core.files.uploadedfile import SimpleUploadedFile
from django.db.models import Q
from django.forms import ModelMultipleChoiceField
from django.template.loader import render_to_string
from django.utils.translation import ugettext_lazy as _
import django_filters
from dj_kits.utils.forms import FormBaseMixin
from django import forms
import operator


class BaseForm(FormBaseMixin, forms.ModelForm):
    i18n_fields = []
    fields_widget_with_form = []

    form_class = 'form-horizontal'
    form_inputs = [Submit('submit', _(u'保存')),
                   Reset('reset', _(u'重置'))]

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(BaseForm, self).__init__(*args, **kwargs)

        lang = self.get_lang()
        if lang:
            for field in self.i18n_fields:
                self.fields.pop('%s_%s' % (field, lang), None)

        for field in self.fields_widget_with_form:
            self.fields[field].widget.form = self

    def is_edit(self):
        return self.instance.pk is not None

    def get_lang(self):
        return getattr(self.request, 'LANGUAGE_CODE', '').replace('-', '_')


class BaseFilterForm(FormBaseMixin, forms.Form):
    form_class = 'form-horizontal'
    form_method = 'get'

    def __init__(self, *args, **kwargs):
        super(BaseFilterForm, self).__init__(*args, **kwargs)
        self.keys = self.fields.keys()
        for k, v in self.fields.items():
            v.help_text = False

    def get_layout(self, helper):
        layout = Layout(
            Div(*self.keys, css_class="inline-group"),
            FormActions(Submit('submit', _(u'查询'))),
            Div(HTML("""<span class="search-slider-btn"></span>"""), css_class="search-slider")
        )
        return layout


class TemplateRenderFieldMixin(object):

    template = None

    def __init__(self, *args, **kwargs):
        template = kwargs.pop('template', None)
        if template:
            self.template = template

        if not self.template:
            raise Exception("template is required.")

        super(TemplateRenderFieldMixin, self).__init__(*args, **kwargs)

    def render(self, *args, **kwargs):
        template = kwargs.pop('template', None)
        if template:
            self.template = template

        field = super(TemplateRenderFieldMixin, self).render(*args, **kwargs)
        return render_to_string(self.template, {'field': field, 'widget': self})


class TemplateRenderSelect(TemplateRenderFieldMixin, forms.Select):
    """ """


class TemplateRenderSelectMultiple(TemplateRenderFieldMixin, forms.SelectMultiple):
    """ """


class TemplateRenderClearableFileInput(TemplateRenderFieldMixin, forms.FileInput):
    """ """
    def value_from_datadict(self, data, files, name):
        val = files.get(name, None) or data.get(name, None)
        if isinstance(val, (basestring, unicode)) and val:
            file_name = data.get('name', 'logo')
            img_str = re.search(r'base64,(.*)', val).group(1)
            temp_img = cStringIO.StringIO(img_str.decode('base64'))
            val = SimpleUploadedFile(file_name, temp_img.read())
        return val

msz/market/forms.py
# -*- coding: utf-8 -*-
from django import forms
from msz.core.forms import BaseForm
from msz.market.models import Company, Category, Product, HomePic


class CompanyForm(BaseForm):

    class Meta:
        model = Company
        fields = ('name', 'mobile', 'tel', 'image', 'description', 'address', 'manager')


class CategoryForm(BaseForm):

    class Meta:
        model = Category
        fields = ('name', 'image', 'info', 'description', 'code')


class ProductForm(BaseForm):

    class Meta:
        model = Product
        fields = ('name', 'category', 'info', 'description', 'code', 'materials', 'image')


class HomePicForm(BaseForm):

    class Meta:
        model = HomePic
        fields = ('name', 'image', 'is_active')

msz/union/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import ugettext_lazy as _
from dj_kits.utils.forms import FormBaseMixin
from django.contrib import auth


class LoginForm(FormBaseMixin, forms.Form):
    username = forms.CharField(required=True, label=_(u"用户名"))
    password = forms.CharField(widget=forms.PasswordInput(), label=_(u"密码"))

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if username == "" or username.isspace():
            raise forms.ValidationError(u"用户名不能为空")
        return username

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if password == "" or password.isspace():
            raise forms.ValidationError(u"密码不能为空")
        if len(password) < 6:
            raise forms.ValidationError(u"请输入一个不小于6位的密码！")
        return password

    def clean(self):
        cleaned_data = self.cleaned_data
        if not self.errors:
            username = self.cleaned_data.get('username')
            password = self.cleaned_data.get('password')
            kw = dict(username=username, password=password)
            user = auth.authenticate(**kw)
            if user is not None:
                if user.is_active:
                    auth.login(self.request, user)
                else:
                    self.add_error('username', u"该用户已被禁止登陆！")
            else:
                self.add_error('username', u"用户名或密码不正确，请重试！")
        return cleaned_data

msz/market/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from msz.market.models import Category, Company, HomePic, Product


def __initial_base_data():
    categories = Category.objects.filter()
    try:
        company = Company.objects.first()
    except:
        company = None

    context = dict(
        categories=categories,
        company=company,
    )
    return context


def index(request):
    context = __initial_base_data()
    pics = HomePic.objects.all()[:3]
    context.update(dict(pics=pics))
    return render(request, 'market/index.html', context)


def category_info(request, pk):
    context = __initial_base_data()
    category = Category.objects.get(pk=pk)
    products = Product.objects.filter(category=category)
    context.update(dict(category=category, products=products))
    return render(request, 'market/category.html', context=context)


def buy(request):
    context = __initial_base_data()
    return render(request, 'market/buy.html', context=context)

msz/union/views.py
# -*- coding: utf-8 -*-
from django.contrib import auth
from django.shortcuts import redirect
from django.views.generic import TemplateView
from dj_kits.utils.forms import errors_to_json
from braces.views import JSONResponseMixin

from msz.core.generic import UnionCommonView, UpdateView, ListView, CreateView
from msz.market.filters import CategoryFilter, ProductFilter
from msz.market.forms import CompanyForm, CategoryForm, ProductForm
from msz.market.models import Company, Category, Product
from msz.market.tables import CategoryTable, ProductTable
from msz.union.forms import LoginForm


class LoginView(TemplateView, JSONResponseMixin):
    template_name = 'union/union_login.html'
    redirect_url = '/union/index/'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return super(LoginView, self).dispatch(request, *args, **kwargs)
        else:
            return redirect(self.redirect_url)

    def get_redirect_to_url(self, request):
        redirect_to = request.REQUEST.get('next', '/union/index/')
        return redirect_to

    def post(self, request, *args, **kwargs):
        redirect_to = self.get_redirect_to_url(request)
        form = LoginForm(request.POST, request=request)
        if form.is_valid():
            data = dict(
                state=True,
                redirect_url=redirect_to
            )
        else:
            data = dict(
                state=False,
                error=errors_to_json(form.errors)
            )
        return self.render_json_response(data)

login = LoginView.as_view()


class LogoutView(TemplateView):

    def get(self, request, *args, **kwargs):
        auth.logout(request)
        next_url = request.REQUEST.get('next', '') or '/union/login/'
        from django.shortcuts import redirect
        return redirect(next_url)

logout = LogoutView.as_view()


class IndexView(UnionCommonView, TemplateView):
    template_name = 'union/union.html'

index = IndexView.as_view()


class CompanyDetailView(UnionCommonView, TemplateView):
    template_name = 'union/company_detail.html'

    def get_context_data(self, **kwargs):
        context = super(CompanyDetailView, self).get_context_data(**kwargs)
        context['company'] = Company.objects.first()
        return context

company_detail = CompanyDetailView.as_view()


class CompanyUpdateView(UnionCommonView, UpdateView, JSONResponseMixin):
    template_name = 'union/company_update.html'
    model = Company
    form_class = CompanyForm
    success_url = '/union/company/'

company_update = CompanyUpdateView.as_view()


class CategoryListView(UnionCommonView, ListView):
    template_name = 'union/category_list.html'
    model = Category
    filter_class = CategoryFilter
    table_class = CategoryTable

category_list = CategoryListView.as_view()


class CategoryCreateView(UnionCommonView, CreateView):
    template_name = 'union/category_create.html'
    model = Category
    form_class = CategoryForm
    success_url = '/union/goods/category/'

category_create = CategoryCreateView.as_view()


class CategoryUpdateView(UnionCommonView, UpdateView):
    template_name = 'union/category_create.html'
    model = Category
    form_class = CategoryForm
    success_url = '/union/goods/category/'

category_update = CategoryUpdateView.as_view()


class ProductListView(UnionCommonView, ListView):
    template_name = 'union/product_list.html'
    model = Product
    filter_class = ProductFilter
    table_class = ProductTable

product_list = ProductListView.as_view()


class ProductCreateView(UnionCommonView, CreateView):
    template_name = 'union/product_create.html'
    model = Product
    form_class = ProductForm
    success_url = '/union/goods/product/'


product_create = ProductCreateView.as_view()


class ProductUpdateView(UnionCommonView, UpdateView):
    template_name = 'union/product_create.html'
    model = Product
    form_class = ProductForm
    success_url = '/union/goods/product/'


product_update = ProductUpdateView.as_view()

msz/templates/base.html
{% load staticfiles %}
{% load dj_kit_tags %}
{% load staticfiles %}
{% load i18n %}
{% load compress %}


<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="keywords" content="xuchao">
    <meta name="description" content="xuchao">
    <meta name="author" content="">
	<title>{% block title %}{{ SITE_TITLE }}{% endblock %}</title>
	<!-- core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">

    <script src="{% static 'js/vendor/jquery-1.8.2.js' %}"></script>
    <!--[if lt IE 9]>
    <script src="{% static 'js/html5shiv.js' %}"></script>
    <script src="{% static 'js/respond.min.js' %}"></script>
    <![endif]-->
    <link rel="shortcut icon" href="{% static 'img/ico/favicon.ico' %}">

    <script src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('.carousel').carousel();
        })
    </script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/jquery.isotope.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
	{% block css %}{% endblock %}
	{% block js %}{% endblock %}
</head>
<body>
	{% get_current_language as LANGUAGE_CODE %}
    <header id="header">
            <nav class="navbar navbar-inverse" role="banner">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><img src="{% static 'img/logo.png' %}" alt="logo" style="width:250px;"></a>
            </div>

            <div class="collapse navbar-collapse navbar-right">
                <ul class="nav navbar-nav">
                    <li  class='active'><a href="{% url 'index' %}">{% trans '首页' %}</a></li>
                    {% for category in categories %}
                    <li ><a href="{% url 'market:category_info' category.id %}">{{ category.name }}</a></li>
                    {% endfor %}
                    <li ><a href="{% url 'market:buy' %}">{% trans '热销商品' %}</a></li>
                    <li ><a href="">{% trans '关于我们' %}</a></li>
                    <li><a href="#">電話：{{ company.tel }}</a></li>
                </ul>
            </div>
        </div><!--/.container-->
    </nav><!--/nav-->
<!--/nav-->
    </header><!--/header-->
    <section id="about-us">
        <div class="container">
        {% block content %}
        {% endblock %}
      <!-- our-team --><!--section-->
        </div><!--/.container-->
    </section><!--/about-us-->

    <section id="bottom">
        <div class="container wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
            <div class="row">
                {% for category in categories %}
                <div class="col-md-3 col-sm-6">
                    <div class="widget">
                        <h3>{{ category.name }}</h3>
                        <ul>
                            {% for product in category.products %}
                            <li>{{ product.name }}</li>
                            {% endfor %}

                        </ul>
                    </div>
                </div><!--/.col-md-3-->
                {% endfor %}
            </div>
        </div>
    </section><!--/#bottom-->

    <footer id="footer" class="midnight-blue">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    &copy; 2016 <a target="_blank" href="" title="{% trans '梦顺斋' %}">{{ company.address }}</a>
                </div>
                <div class="col-sm-6">
                    <ul class="pull-right">
                        {% for c in categories %}
                        <li><a href="flower.html">{{ c.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </footer><!--/#footer-->
</body>
</html>

msz/templates/index.html
{% extends "base.html" %}

{% block content %}
Hi, {{ user }}. It works!
{% endblock %}